### ISSUE TITLE
netstat deprecated in linux

### ISSUE THREAD

**Issue by albertlinga** [microsoft/vscode-tye#181] opened 2022-03-30 07:11 UTC
Netstat  has been deprecated in linux and is not installed by default in latest distros such as ubuntu. Ss is the recommended tool now. This causes an error on the extension when loaded and during debug with message “spawn netstat ENOENT”. https://github.com/microsoft/vscode-tye/blob/24eb317b922dda42d1fc4c9ed4e6ef34c91ba434/src/services/portProvider.ts uses a package for netstat. Perhaps a different package for SS can be used instead? Work around fix is to install net-tools: “sudo apt install net-tools”

**Comment by philliphoff** [comment] 2022-04-07 21:35
This is a good catch and suggestion.  I'm going to close this as a duplicate of #179.

**Closed by philliphoff** 2022-04-07 21:35 UTC
