### ISSUE TITLE
[devcontainer] Killing `tye-run` terminal doesn't seem to kill `tye` process

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-tye#54] opened 2021-04-29 04:26 UTC
Not sure why, but when running in a Dev Container, the `tye` process of a `tye-run` task isn't getting killed when killing its terminal window, which is not the behavior we've seen up to this point.  This prevents subsequent `tye-run` tasks from running.

Need to investigate this for public release.

This is with the latest Insiders release.

**Comment by pratiksanglikar** [comment] 2021-07-28 21:24
This happens due to we fail to correlate the task with the tye application due to the bug in `child_process` of `node`.
More details here - #127.

**Comment by pratiksanglikar** [comment] 2021-07-28 21:24
Duplicate of #127

**Closed by pratiksanglikar** 2021-07-28 21:24 UTC
Labels: P2, bug, investigate
