### ISSUE TITLE
It will keep downloading the tye extension for about 1 min after the extension has been downloaded successfully

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#111] opened 2021-07-01 10:31 UTC
**OS:** Win10
**Build Version:** 20210630.1

**Repro Steps:**
1. Download tye extension from Azure Devops.
2. Check whether succeed to download the tye extension in 10 seconds.

**Expect:**
Succeed to download the tye extension in 10 seconds.

**Actual:**
It will keep downloading for about 1 min in browser, but the extension has been downloaded successfully.
![image](https://user-images.githubusercontent.com/45614674/124109607-e9112b00-da99-11eb-90b5-1bdb62762667.png)

**More Info:**
This issue does not reproduce when downloading other extensions, such as Azure Storage extension which size larger than tye extension.

**Comment by pratiksanglikar** [comment] 2021-07-15 23:30
Resolved partially via #123

**Comment by pratiksanglikar** [comment] 2021-07-28 21:20
Duplicate of #77

**Closed by pratiksanglikar** 2021-07-28 21:20 UTC
Labels: AT-CTI, investigate
