### ISSUE TITLE
A confused message shows in Tye view after installing Tye at an explicit Tye path

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#105] opened 2021-06-30 09:58 UTC
**OS:** Win10
**Build Version:** 20210628.1

**Repro Steps:**
1. Install Tye at a custon path using the below command.
`dotnet tool install Microsoft.Tye  --version "0.8.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json --tool-path "C:\custom_tye_path"`
2. Set the tye path property in vscode-tye.
![image](https://user-images.githubusercontent.com/45614674/123939307-9a489000-d9ca-11eb-8e40-9eabda6bec85.png)
3. Restart VS Code and navigate to Tye view.

**Expect:**
It shows "No Tye applications are running".

**Actual:**
A confused message "A compatible version of Tye has not been found. You may need to install a more recent version" shows.
![image](https://user-images.githubusercontent.com/45614674/123939923-412d2c00-d9cb-11eb-8701-88850d1ec7e6.png)

**More Info:**
The version of Tye is the latest one.
![image](https://user-images.githubusercontent.com/45614674/123940321-a2ed9600-d9cb-11eb-9e91-813eaeb966d0.png)

**Comment by philliphoff** [comment] 2021-06-30 17:57
@v-ruizh The issue is that the extension expects the setting to be the *full* path to the `tye` binary, and not just the folder in which it resides.  I see that the test instructions were incorrect and have updated them.  That said, we could still do better to distinguish the case between not finding Tye *at all* and finding an incompatible version of Tye.  I'll mark this as an enhancement for a future release.

**Comment by v-xinda** [comment] 2023-04-10 08:47
Verified this issue with the latest build 20230320.1, it doesn't reproduce now after filling in the full path to the Tye binary. So close it.

**Closed by v-xinda** 2023-04-10 08:47 UTC
Labels: enhancement, P3, AT-CTI
